apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-api-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml

commonLabels:
  environment: production
